version: '3'

services:
  hoops-staging:
    image: ghcr.io/techsoft3d/streaming-server:staging
    container_name: hoops-staging
    restart: unless-stopped
    ports:
      - "11183:11183"
      - "11035-11070:11035-11070"
    volumes:
      - "./patches-staging/server_config.js:/opt/hoops_communicator/quick_start/server_config.js"
      - "./patches-staging/Utils.js:/opt/hoops_communicator/server/node/lib/Utils.js"
      - "models:/opt/hoops_communicator/models"
      - "./hoops_license.txt:/opt/hoops_communicator/hoops_license.txt"
      - public-staging:/opt/public-staging  # Shared volume to copy files
    environment:
      - HOST_IP=${HOST_IP}
    networks:
      - shared-network 
    command: ["/bin/sh", "-c", "
        echo 'Copying HOOPS files to public-staging/hoops...' &&
        mkdir -p /opt/public-staging/hoops &&
        cp /opt/hoops_communicator/web_viewer/deprecated/src/js/hoops_web_viewer.js /opt/public-staging/hoops/ &&
        cp /opt/hoops_communicator/web_viewer/deprecated/src/js/engine-wasm.js /opt/public-staging/hoops/ &&
        cp /opt/hoops_communicator/web_viewer/deprecated/src/js/engine-asmjs.js /opt/public-staging/hoops/ &&
        cp /opt/hoops_communicator/web_viewer/deprecated/src/js/engine.wasm /opt/public-staging/hoops/ &&
        echo 'Copy complete. Starting Streaming Server...' &&
        exec ../../3rd_party/node/bin/node --expose-gc ./lib/Startup.js --config-file ../../quick_start/server_config.js"]
    
  file-server-staging:
    image: ghcr.io/techsoft3d/node-server:staging
    container_name: file-server-staging
    restart: unless-stopped
    ports:
      - "3001:3001"  # Change to whatever port you want files to be served from, but default is 3000
    environment:
      - PORT=3001  # This sets the PORT dynamically
    volumes:
      - public-staging:/app/public  # Mounts local "public" folder into the container
    depends_on:
      - hoops-staging
    networks:
      - shared-network 

volumes:
  public-staging:
    external: true
  models:
    external: true

networks:
  shared-network:
    external: true
